[package]
name = "reveal-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reveal"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29.0", features = ["fs"] }
